version: '3.8'

services:
  # Service aplikasi Node.js
  app:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MONGODB_URI=mongodb://mongo:27017/task-7
    depends_on:
      - mongo
    volumes:
      - .:/app
      - /app/node_modules

  # Service MongoDB
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

# Volume untuk menyimpan data MongoDB
volumes:
  mongo-data: